import {
  Callout,
  ContentStep,
  Definition,
  Example,
  Flowchart,
  KeyTakeaways,
  LessonArticle,
  LessonSection,
} from '../../../../../components/content'

export function MultipartAndPresigned() {
  return (
    <LessonArticle>
      <Callout variant="beginner" title="Large files and temporary access are daily DE problems">
        Spark writes multi-GB Parquet shards; partners upload CSV dumps; analysts need time-boxed download
        links without IAM users. S3 <strong className="text-white">multipart upload</strong> and{' '}
        <strong className="text-white">presigned URLs</strong> solve throughput and delegated access — know
        both for pipeline design and incident response.
      </Callout>

      <Definition term="Multipart upload">
        <p>
          <strong className="text-white">Multipart upload</strong> splits a large object into parts (5 MiB
          to 5 GiB each, up to 10,000 parts) uploaded in parallel, then completed with an ETag manifest.
          Required practical path for objects &gt; 5 GB via single PUT; recommended for large files on
          unreliable networks and parallel writer threads in custom ingest tools.
        </p>
      </Definition>

      <LessonSection title="Multipart upload for large files">
        <ContentStep number={1} title="When DE uses multipart">
          <p className="text-slate-300">
            Custom bulk loaders, on-prem migration tools (DataSync, Snowball follow-up), EMR/Spark direct
            writes when not using s3a committers, video/log archives &gt; 100 MB. AWS SDKs auto-multipart
            above configurable thresholds — tune for your bandwidth and memory.
          </p>
        </ContentStep>
        <ContentStep number={2} title="Lifecycle cleanup">
          <p className="text-slate-300">
            Failed jobs leave <strong className="text-white">incomplete multipart uploads</strong> — billed
            storage with no visible object key. Lifecycle rule: abort incomplete uploads after 7 days. Monitor
            with S3 Storage Lens or Inventory metrics on incomplete MPU bytes.
          </p>
        </ContentStep>
        <ContentStep number={3} title="Concurrency and part sizing">
          <p className="text-slate-300">
            Larger parts reduce request count but retry more data on failure. DE migration scripts often use
            64–128 MiB parts with 8–16 parallel threads — balance with instance network caps and S3 request
            rate per prefix (hot prefix sharding still applies).
          </p>
        </ContentStep>
        <Flowchart
          title="Multipart upload lifecycle"
          chart={`flowchart LR
  INIT[CreateMultipartUpload]
  P1[UploadPart 1..N parallel]
  COMP[CompleteMultipartUpload]
  OBJ[S3 object visible]
  FAIL[Job fails mid-upload]
  ABORT[AbortMultipartUpload or lifecycle abort]
  INIT --> P1
  P1 --> COMP
  COMP --> OBJ
  P1 --> FAIL
  FAIL --> ABORT`}
        />
        <Example title="AWS CLI multipart threshold (concept)">
{`# SDKs switch to multipart automatically above threshold
aws configure set default.s3.multipart_threshold 64MB
aws configure set default.s3.multipart_chunksize 64MB
aws s3 cp large-dump.parquet s3://lake/landing/large-dump.parquet`}
        </Example>
      </LessonSection>

      <LessonSection title="Presigned URLs for temporary access">
        <Definition term="Presigned URL">
          <p>
            A <strong className="text-white">presigned URL</strong> embeds temporary SigV4 credentials in
            the query string — anyone with the URL can perform the signed action (GET, PUT) until expiry.
            Generated by a principal that already has permission; no separate IAM user for the partner.
          </p>
        </Definition>
        <ContentStep number={1} title="Upload without AWS credentials">
          <p className="text-slate-300">
            API Gateway + Lambda validates partner token → Lambda (with{' '}
            <span className="font-mono text-sm">s3:PutObject</span> on landing) returns presigned PUT URL
            → partner uploads directly to S3. Keeps bucket private; no wide-open bucket policy.
          </p>
        </ContentStep>
        <ContentStep number={2} title="Time-limited download">
          <p className="text-slate-300">
            Analyst tool generates presigned GET for one exported CSV — expires in 15 minutes. Audit via
            CloudTrail data events showing the signing principal, not anonymous public access.
          </p>
        </ContentStep>
        <ContentStep number={3} title="Security hygiene">
          <p className="text-slate-300">
            Short expiry (minutes to hours), least action (GET vs PUT), single-object key scope. Treat URLs
            as secrets — log leakage, use HTTPS only. For SSE-KMS objects, signer needs kms permissions that
            propagate to downloaders through the presigned request.
          </p>
        </ContentStep>
        <Example title="boto3 presigned GET (Python sketch)">
{`import boto3
from botocore.config import Config

s3 = boto3.client("s3", config=Config(signature_version="s3v4"))
url = s3.generate_presigned_url(
    "get_object",
    Params={"Bucket": "company-lake", "Key": "exports/report.csv"},
    ExpiresIn=900,
)
# Hand url to consumer — valid 15 minutes`}
        </Example>
        <Callout variant="insight">
          Presigned URLs delegate <em>your</em> IAM permissions temporarily — if the signing role can read
          all of curated/, every URL it mints carries that scope unless you use dedicated narrow signing roles.
        </Callout>
      </LessonSection>

      <KeyTakeaways
        items={[
          'Multipart upload enables parallel, resumable large object uploads — SDKs auto-switch above thresholds.',
          'Abort incomplete multipart uploads via lifecycle (7 days) — failed ETL jobs hide storage cost otherwise.',
          'Presigned URLs grant temporary GET/PUT without IAM users — ideal for partner ingest and secure exports.',
          'Keep presigned expiry short; use narrow signing roles; HTTPS only.',
          'SSE-KMS presigned operations require signer KMS permissions compatible with consumer access.',
        ]}
      />
    </LessonArticle>
  )
}
